spring:
  application:
    name: surest-member-management

#Database connection properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/member_management
    username: postgres
    password: utkrisht16

#Jpa Properties
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#Flyway Properties
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


#JWT properties
jwt.secret: mY7e8Zq4vR2xA1bC6kL9pW3sJ0dF5tH8
jwt.expiration: 86400000
